"""
PR Summarizer
One LLM call that turns a list of applied security fixes into a
professional GitHub pull request (title + body markdown).

Input is intentionally minimal: semgrep metadata + unified diff per fix.
No caveman voice here — output is public-facing.
"""

import os
import json
import difflib
from typing import Dict, List, Optional

from tools.nvidia_client import chat, _extract_json

DEBUG = os.environ.get("PATCHY_DEBUG", "0") == "1"

MAX_DIFF_LINES_PER_FIX = 120
MAX_TOKENS = 4000
TEMPERATURE = 0.3

SYSTEM_PROMPT = """You are Patchy's PR writer. You turn a list of automated
security fixes into a clean GitHub pull request.

Input: JSON with "fixes" (each has check_id, severity, file, message, diff)
and "repo", "scan_id".

Output: EXACTLY ONE JSON object, nothing else, no markdown fences:
{
  "title": "<PR title>",
  "body":  "<PR body, GitHub-flavored markdown>"
}

Title rules:
- Imperative mood. <= 72 chars.
- Pattern: "Fix <N> security findings from Semgrep scan" when mixed,
  or specific like "Disable Flask debug mode in production" when one fix.
- No emoji. No trailing period.

Body rules:
- Professional English. Full sentences. No caveman. No hedging filler.
- Start with a 1-sentence summary of what this PR does and why.
- Then "## Changes" section: one bullet per fix, format:
    - `<file>` — <what changed>, fixes `<check_id>` (<severity>).
- Then "## Semgrep findings addressed" section: short table
  | Rule | Severity | File |
- End with "Generated by Patchy · scan `<scan_id>`".
- Do NOT paste full diffs in the body. Reviewer sees diff in PR tab.
- Do NOT invent findings not in input.
- Do NOT speculate about unrelated code.

Stay grounded in the provided fixes. No extra advice, no TODOs,
no "consider also...". Just describe what was done."""


def _log(msg):
    if DEBUG:
        print(f"[PR_SUMMARIZER] {msg}")


def make_unified_diff(original: str, patched: str, file_path: str,
                      max_lines: int = MAX_DIFF_LINES_PER_FIX) -> str:
    """Build a unified diff of the two contents, truncated by line count."""
    orig_lines = (original or "").splitlines(keepends=True)
    new_lines = (patched or "").splitlines(keepends=True)
    diff_iter = difflib.unified_diff(
        orig_lines, new_lines,
        fromfile=f"a/{file_path}", tofile=f"b/{file_path}",
        n=2,
    )
    lines = list(diff_iter)
    if len(lines) > max_lines:
        kept = lines[:max_lines]
        kept.append(f"... [{len(lines) - max_lines} more diff lines truncated]\n")
        lines = kept
    return "".join(lines)


def build_fix_summary(valid_fixes: List[Dict]) -> List[Dict]:
    """Reduce pipeline fix records to the minimal set the summarizer needs."""
    out = []
    for fix in valid_fixes:
        finding = fix.get("finding", {}) or {}
        extra = finding.get("extra", {}) or {}
        diff = make_unified_diff(
            fix.get("original_code", "") or "",
            fix.get("fixed_code", "") or "",
            fix.get("file_path", "?"),
        )
        out.append({
            "check_id": finding.get("check_id", "unknown"),
            "severity": (extra.get("severity", "") or "").upper(),
            "file": fix.get("file_path", "?"),
            "message": (extra.get("message", "") or "").strip()[:500],
            "diff": diff,
        })
    return out


def summarize_pr(valid_fixes: List[Dict], repo: str,
                 scan_id: str) -> Optional[Dict]:
    """Return {'title', 'body'} or None on failure.

    Caller must have its own fallback (e.g. the pipeline's _build_pr_body).
    """
    if not valid_fixes:
        return None

    fixes_payload = build_fix_summary(valid_fixes)
    user_payload = {
        "repo": repo,
        "scan_id": scan_id,
        "fixes": fixes_payload,
    }

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": json.dumps(user_payload, indent=2)},
    ]

    try:
        raw = chat(messages, temperature=TEMPERATURE, max_tokens=MAX_TOKENS)
    except Exception as e:
        _log(f"chat failed: {e}")
        return None

    try:
        obj = json.loads(_extract_json(raw))
    except Exception as e:
        _log(f"json parse failed: {e}; raw head: {raw[:200]!r}")
        return None

    if not isinstance(obj, dict):
        _log(f"not a dict: {type(obj).__name__}")
        return None
    title = (obj.get("title") or "").strip()
    body = (obj.get("body") or "").strip()
    if not title or not body:
        _log(f"empty title/body (title={len(title)}, body={len(body)})")
        return None
    return {"title": title, "body": body}
